### DISCUSSION TITLE
Can you validate against schema defined in .yaml?

### DISCUSSION THREAD

**Discussion by ifeeltiredboss** [python-jsonschema/jsonschema#1043] [Q&A]
Is there a possibility to use:
```yaml
---
type: array
items:
  type: object
  properties:
    type:
      "$ref": some_file.yaml#/components/schemas/SomeOtherSchema
    ids:
      type: array
      items:
        type: string
  required:
  - type
```
Instead of this:
```json
{
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "some_file.json#/components/schemas/SomeOtherSchema"
            },
            "ids": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "type"
          ]
        }
      }
```
How do I proceed with that? I tend to use validate()
