### ISSUE TITLE
[Potential bug] Not properly validated schema

### ISSUE THREAD

**Issue by maciejstromich** [python-jsonschema/jsonschema#1081]
Hi, not sure if this is a bug or it's schema validation specific behaviour (fastjsonschema==2.6.13)

I've a schema
```
$schema: "http://json-schema.org/draft-07/schema"
definitions:
  testrecord:
    type: 'object'
    properties:
      timestamp:
        type: 'number'
      customer_id:
        type: 'string'
        minLength: 1
        maxLength: 128
    required: ['timestamp']
```

with a payload that conforms to the object properties everything is working as expected:

```
testrecord.validate({'timestamp': 123123123123, 'customer_id': 'test'})
{'timestamp': 123123123123, 'customer_id': 'test'}
```

now I would assume that when the payload contains unexpected properties validation would throw a ValidationError but it's not. It just returns the passed object

```
testrecord.validate({'timestamp': 123123123123, 'customer_id': 'test', 'something_not_in_schema': 'somevalue'})
{'timestamp': 123123123123, 'customer_id': 'test', 'something_not_in_schema': 'somevalue'}
```

Am I missing something to throw ValidationErrors in such a case or by using fastjsonschema one opens up for potential issues when someone sends a payload outside of the defined object properties?
